name: url_pattern
description: Url pattern matching.
version: 1.0.0
author: Ganesh Poojary <ganesh4212@gmail.com>
homepage: https://github.com/ganesh-4212/restro

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:

dev_dependencies:
  test: 1.3.4